name: Start Wars Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  Build-and-Test:
      timeout-minutes: 60
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm i
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - run: xvfb-run node index.js
      - name: Build and Run e2e playwright test
        run: npm run e2e-fullregression-runner-test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
            name: playwright-report
            path: playwright-report/
            retention-days: 5