name: Start Wars Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm i
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Initialize local app and run the e2e test
      run: npm run e2e-fullreg-local-chrome
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Report
        path: test-results
        retention-days: 5
